### PR TITLE
Fix skipped tests

### LINKED ISSUE #681: Regenerate proofs for MPP (re-enable skipped tests)

### PR DESCRIPTION
**Pull request by sarvesh-ost**
Fixes #681

Reenabled skipped tests of confirm stake intent.

### CODE REVIEW

**Comment by benjaminbollen** [comment]
LGTM

File: test/gateway/eip20_cogateway/confirm_stake_intent.js [hunk 1]
```diff
@@ -91,8 +92,8 @@ contract('EIP20CoGateway.confirmStakeIntent() ', (accounts) => {
 
     assert.strictEqual(
       result,
-      data.messageHash,
-      `Message hash form the contract must match ${data.messageHash}.`,
+      messageHash,
+      `Message hash form the contract must match ${messageHash}.`,
```
Comment (schemar) [inline test/gateway/eip20_cogateway/confirm_stake_intent.js]:
```suggestion
      `Message hash from the contract must match ${messageHash}.`,
```
Printing `${messageHash}` here is also redundant, as it will be part of the mocha/chai output. The message could simply be that "The contract did not return the expected message hash on `configmStakeIntent`."

File: test/gateway/eip20_cogateway/confirm_stake_intent.js [hunk 2]
```diff
@@ -121,13 +122,14 @@ contract('EIP20CoGateway.confirmStakeIntent() ', (accounts) => {
...
+    const messageData = await coGateway.messages(messageHash);
 
+    const intentHash = coGatewayUtils.hashStakeIntent(amount, beneficiary, gatewayAddress);
     assert.strictEqual(
       messageData.intentHash,
-      data.intentHash,
+      intentHash,
       `Message.intentHash from the contract must be equal to ${
-        data.intentHash
+        intentHash
```
Comment (schemar) [inline test/gateway/eip20_cogateway/confirm_stake_intent.js]: Same as above

File: test/gateway/eip20_cogateway/confirm_stake_intent.js [hunk 3]
```diff
@@ -445,8 +446,8 @@ contract('EIP20CoGateway.confirmStakeIntent() ', (accounts) => {
 
     assert.strictEqual(
       eventData._messageHash,
-      data.messageHash,
-      `Message hash from event must be equal to ${data.messageHash}.`,
+      messageHash,
+      `Message hash from event must be equal to ${messageHash}.`,
```
Comment (schemar) [inline test/gateway/eip20_cogateway/confirm_stake_intent.js]: same as above

File: test/gateway/eip20_cogateway/confirm_stake_intent.js [hunk 4]
```diff
@@ -51,28 +53,27 @@ contract('EIP20CoGateway.confirmStakeIntent() ', (accounts) => {
...
+    stakerNonce = new BN(testData.gateway.stake.params.nonce);
+    beneficiary = testData.gateway.stake.params.beneficiary;
+    amount = new BN(testData.gateway.stake.params.amount, 16);
+    gasPrice = new BN(testData.gateway.stake.params.gasPrice);
+    gasLimit = new BN(testData.gateway.stake.params.gasLimit, 16);
+    blockHeight = new BN(testData.gateway.stake.return_value.blockNumber);
+    rlpParentNodes = testData.gateway.stake.proof_data.storageProof[0].serializedProof;
+    storageRoot = testData.gateway.stake.proof_data.storageHash;
+    hashLock = testData.gateway.stake.params.hashLock;
+    messageHash = testData.gateway.stake.return_value.returned_value.messageHash_;
```
Comment (schemar) [inline test/gateway/eip20_cogateway/confirm_stake_intent.js]: You could improve readability by starting this block with
```js
const { stake } = testData.gateway;
```
or
```js
const { params } = testData.gateway.stake;
```
